name: Telegram Notifications

on: [push]

jobs:

  build:
    name: Telegram Notifications
    runs-on: ubuntu-18.04
    steps:
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered first step.
      - name: send custom message with args to me
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ME }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Hello User!!!
      - name: send custom message with args to me
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_C }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Hello, it's your boss. Please continue to work on the video instead of being on telegram.